// ==============================================================
// gridheist.js v0.0.1
// A jQuery plugin to hijack an image gallery, making it great.
// http://github.com/cavis/gridheist
// ==============================================================
// Copyright (c) 2013 Ryan Cavis
// Licensed under http://en.wikipedia.org/wiki/MIT_License
// ==============================================================
// Generated by CoffeeScript 1.6.3
(function() {
  var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    __slice = [].slice;

  (function($, window) {
    var GridHeist;
    GridHeist = (function() {
      GridHeist.prototype["public"] = {
        update: true
      };

      GridHeist.prototype.defaults = {
        thumbSelector: '> *',
        thumbBorder: 10,
        expandHeight: 300,
        expandSideWidth: 200,
        expandSideRender: false
      };

      function GridHeist(el, options) {
        this.clickHandler = __bind(this.clickHandler, this);
        var _this = this;
        this.options = $.extend({}, this.defaults, options);
        this.$el = $(el);
        this.$el.addClass('gridheist-gallery');
        this.$el.on('click', '.gridheist-thumb', this.clickHandler);
        this.update();
        $(window).resize(function() {
          if (_this.width !== _this.$el.width()) {
            return _this.doLayout();
          }
        });
      }

      GridHeist.prototype.update = function() {
        this.$thumbs = this.$el.find(this.options.thumbSelector);
        this.$thumbs.addClass('gridheist-thumb');
        return this.doLayout();
      };

      GridHeist.prototype.doLayout = function() {
        var margin;
        if (this.$expander) {
          this.$expander.remove();
        }
        this.width = this.$el.width();
        this.rows = [];
        margin = "0 " + this.options.thumbBorder + "px " + this.options.thumbBorder + "px 0";
        this.$thumbs.css('margin', margin);
        return this.processThumb(0, 0, 0);
      };

      GridHeist.prototype.processThumb = function(idx, rowIdx, rowWidth) {
        var $img, $thumb,
          _this = this;
        if (idx < this.$thumbs.length) {
          $thumb = this.$thumbs.eq(idx);
          $img = $thumb.find('img');
          return this.getImageWidth($img, function(imgWidth) {
            if (!_this.rows[rowIdx]) {
              _this.rows[rowIdx] = {
                thumbs: [],
                images: [],
                widths: []
              };
            }
            _this.rows[rowIdx].thumbs.push($thumb);
            _this.rows[rowIdx].images.push($img);
            _this.rows[rowIdx].widths.push(imgWidth);
            $thumb.data('row', rowIdx);
            if (rowWidth !== 0) {
              rowWidth += _this.options.thumbBorder;
            }
            rowWidth += imgWidth;
            if (rowWidth >= _this.width) {
              _this.layoutRow(rowIdx, rowWidth);
              return _this.processThumb(idx + 1, rowIdx + 1, 0);
            } else {
              return _this.processThumb(idx + 1, rowIdx, rowWidth);
            }
          });
        } else if (this.rows[rowIdx]) {
          return this.layoutRow(rowIdx, rowWidth);
        }
      };

      GridHeist.prototype.layoutRow = function(rowIdx, rowWidth) {
        var $thumb, center, idx, margin, rowDebt, thumbDebt, _i, _len, _ref, _results;
        rowDebt = Math.max(rowWidth - this.width, 0);
        _ref = this.rows[rowIdx].thumbs;
        _results = [];
        for (idx = _i = 0, _len = _ref.length; _i < _len; idx = ++_i) {
          $thumb = _ref[idx];
          thumbDebt = Math.ceil(rowDebt / (this.rows[rowIdx].thumbs.length - idx));
          rowDebt -= thumbDebt;
          $thumb.css('width', this.rows[rowIdx].widths[idx] - thumbDebt);
          center = Math.floor(thumbDebt / 2);
          this.rows[rowIdx].images[idx].css('margin-left', -center);
          if (idx === this.rows[rowIdx].thumbs.length - 1) {
            margin = "0 0 " + this.options.thumbBorder + "px 0";
            _results.push($thumb.css('margin', margin));
          } else {
            _results.push(void 0);
          }
        }
        return _results;
      };

      GridHeist.prototype.getImageWidth = function($img, callback) {
        var tmp, w;
        if (w = $img.data('width')) {
          return callback(w);
        } else {
          tmp = new Image();
          return $(tmp).load(function() {
            $img.data('width', tmp.width);
            return callback(tmp.width);
          }).error(function() {
            console.error('An error occurred and your image could not be loaded.  Please try again.');
            return callback(0);
          }).attr({
            src: $img.attr('src')
          });
        }
      };

      GridHeist.prototype.clickHandler = function(e, other) {
        var $last, $target, href, rowIdx;
        e.preventDefault();
        $target = $(e.currentTarget);
        rowIdx = $target.data('row');
        href = $target.attr('href');
        $last = this.rows[rowIdx].thumbs[this.rows[rowIdx].thumbs.length - 1];
        return this.renderExpander($last, href, $target);
      };

      GridHeist.prototype.renderExpander = function($after, src, $target) {
        var align, bordr, width;
        if (this.$expander) {
          this.$expander.remove();
        }
        this.$el.find('.gridheist-thumb.expanded').removeClass('expanded');
        $target.addClass('expanded');
        this.$expander = $('<div class="gridheist-expander"></div>');
        this.$expander.css('margin-bottom', this.options.thumbBorder);
        this.$expander.css('height', this.options.expandHeight);
        if (this.options.expandSideRender) {
          width = this.options.expandSideWidth;
          this.$expander.append("<div class=\"gridheist-expander-side\" style=\"width:" + width + "px\">\n  <div class=\"gridheist-expander-seperator\"></div>\n  <div class=\"gridheist-expander-content\">\n    " + (this.options.expandSideRender($target)) + "\n  </div>\n</div>");
        }
        align = $target.position().left + ($target.width() / 2);
        bordr = this.options.thumbBorder;
        this.$expander.append("<div class=\"gridheist-expander-arrow\" style=\"left:" + align + "px;\n  border-width:" + bordr + "px; margin-left:-" + bordr + "px;\">\n</div>");
        this.$expander.append("<div class=\"gridheist-expander-img\">\n  <img src=\"" + src + "\"/>\n</div>");
        return $after.after(this.$expander);
      };

      return GridHeist;

    })();
    return $.fn.extend({
      gridHeist: function() {
        var args, option;
        option = arguments[0], args = 2 <= arguments.length ? __slice.call(arguments, 1) : [];
        return this.each(function() {
          var $this, data;
          $this = $(this);
          data = $this.data('gridHeist');
          if (!data) {
            $this.data('gridHeist', (data = new GridHeist(this, option)));
          }
          if (typeof option === 'string' && data["public"][option]) {
            return data[option].apply(data, args);
          }
        });
      }
    });
  })(window.jQuery, window);

}).call(this);
